name = "cf-analytics"
account_id = "e0914bbf92140660c12e968524e43a8a"
workers_dev = true
main = "src/workers/index.ts"
compatibility_date = "2026-04-28"

[env.production]
routes = []  # 将在部署时配置自定义域名

# 绑定到R2存储桶
[[env.production.r2_buckets]]
binding = "LOGS_BUCKET"
bucket_name = "cf-logs"

# KV命名空间绑定
[[env.production.kv_namespaces]]
binding = "CACHE"
id = "90c5cf692cb84e009ae02cbfc64371c1"

[env.development]
routes = [{ pattern = "localhost:8787/api/*" }]

# Development bindings
[[env.development.r2_buckets]]
binding = "LOGS_BUCKET"
bucket_name = "cf-logs"

[[env.development.kv_namespaces]]
binding = "CACHE"
id = "90c5cf692cb84e009ae02cbfc64371c1"
